name: flutter_wallpaper_x

description: Flutter version 3.16.0

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_bloc: ^8.1.3
  
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  flutter_spinkit: ^5.2.0
  google_fonts: ^6.1.0
  dio: ^5.3.4
  path_provider: ^2.1.1
  flutter_staggered_grid_view: ^0.7.0
  extended_image: ^8.2.0
  font_awesome_flutter: ^10.6.0
  lottie: ^2.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_cache_manager: ^3.3.1
  image_gallery_saver: ^2.0.3
  fluttertoast: ^8.2.4
  image_cropper: ^5.0.0
  just_the_tooltip: ^0.0.12
  async_wallpaper: ^2.0.3
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  change_app_package_name: ^1.1.0
  page_transition: ^2.1.0
  flutter_native_splash: ^2.3.6
  firebase_core: ^2.23.0
  firebase_messaging: ^14.7.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/Images/Logo/
    - assets/Images/Category/
    - assets/Lotties/
