name: flutter_wallpaper_x

description: Flutter version 3.10.5

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_bloc: ^8.1.2
  
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  shared_preferences: ^2.0.20
  flutter_spinkit: ^5.1.0
  google_fonts: ^6.1.0
  dio: ^5.1.1
  path_provider: ^2.0.14
  flutter_staggered_grid_view: ^0.7.0
  extended_image: ^8.0.2
  font_awesome_flutter: ^10.4.0
  lottie: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_cache_manager: ^3.3.0
  image_gallery_saver: ^2.0.3
  fluttertoast: ^8.2.1
  image_cropper: ^5.0.0
  just_the_tooltip: ^0.0.12
  async_wallpaper: ^2.0.2
  url_launcher: ^6.1.10
  share_plus: ^7.1.0
  change_app_package_name: ^1.1.0
  page_transition: ^2.0.9
  flutter_native_splash: ^2.2.19
  firebase_core: ^2.16.0
  firebase_messaging: ^14.6.8
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/Images/Logo/
    - assets/Images/Category/
    - assets/Lotties/
